sonar.projectKey=Jorima
sonar.projectName=Jorima
sonar.host.url=http://localhost:9000
sonar.token=squ_57f75c89589fbfcc6d0749c7bc24cceee053091f

sonar.sources=app,lib,keys,constants,prisma,middleware.ts
sonar.exclusions=node_modules/**,.next/**,dist/**,build/**,public/**,uploads/**
sonar.sourceEncoding=UTF-8


