 # Identificador único de tu proyecto dentro de SonarQube
sonar.projectKey=Jorima
sonar.projectName=Jorima

# Versión de tu código
sonar.projectVersion=1.0

# Carpeta con el código fuente a analizar (. analiza la carpeta actual)
sonar.sources=.

# Codificación del código fuente
sonar.sourceEncoding=UTF-8
